name: "Lint: tflint"

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  tflint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: latest
      - run: tflint --init
      - run: tflint --recursive --format compact
