name: "Lint: tflint"

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  tflint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: latest
      - run: tflint --init
      - run: tflint --recursive --format compact
