name: "SAST: Checkov"

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  checkov:
    name: Checkov scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@2fd3901c8feb52417f27f0d9800259a106c1ec1e # v12.3089.0
        with:
          directory: .
          framework: terraform
          compact: true
          quiet: true
          soft_fail: false
