name: "SAST: Checkov"

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  checkov:
    name: Checkov scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@de2bfaecd21d58ef232e0d2a3391c33c32c460d7 # v12.3096.0
        with:
          directory: .
          framework: terraform
          compact: true
          quiet: true
          soft_fail: false
