name: "SAST: Checkov"

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  checkov:
    name: Checkov scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@dfb51aed1b783289b0d3f255028e7a88d5e8caa1 # v12.3105.0
        with:
          directory: .
          framework: terraform
          compact: true
          quiet: true
          soft_fail: false
