name: "Unit: variables"

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  variables:
    name: tofu test (variables)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # v2.0.0
      - run: tofu init -backend=false
      - run: tofu test -filter=tests/variables.tftest.hcl -no-color
